name: Master Push

# run (and build) only py3.7 but on all platforms
# pull_request.yml tests all py versions but only on ubuntu

on:
  push:
    branches:
      - 'master'
    paths-ignore:
      - '*.md'
      - '*.sh'
      - '*.ipynb'
      - '*.*json'

jobs:
  build_wheels:
    name: Push - cp37*, ${{ matrix.platform }}
    runs-on: ${{ matrix.image }}
    strategy:
      fail-fast: true
      matrix:
        include:
          - image: ubuntu-latest
            platform: linux
          - image: windows-latest
            platform: windows
          - image: macos-latest
            platform: macos

    steps:
    - uses: actions/checkout@v2

    - name: Configure Python
      uses: actions/setup-python@v2

    # keep in-sync with the other yaml
    # only macos makes sense, windows didn't work, linux installs conan inside the docker image
    - name: Cache Conan (MacOS)
      id: cache-conan
      uses: actions/cache@v2
      if: matrix.platform == 'macos'
      with:
        path: |
          ${{ github.workspace }}/conan_data
          ${{ github.workspace }}/conan_build
        key: conan-${{ matrix.platform }}-${{ hashFiles('conanfile.txt') }}
        restore-keys: |
          conan-${{ matrix.platform }}-

    - name: Install Conan (MacOS)
      if: matrix.platform == 'macos' && steps.cache-conan.outputs.cache-hit != 'true'
      run: |
        pip install pip --upgrade
        pip install conan<2.0.0
        conan profile new default --detect
        conan config set "storage.path=${{ github.workspace }}/conan_data"
        conan install --install-folder ${{ github.workspace }}/conan_build --remote conancenter .

    - name: Install Conan (Windows)
      if: matrix.platform == 'windows'
      run: |
        pip install pip --upgrade
        pip install conan<2.0.0
        conan profile new default --detect
        conan profile update "settings.compiler=Visual Studio" default
        conan profile update "settings.compiler.version=16" default
        conan config set "storage.path=$env:GITHUB_WORKSPACE/conan_data"
        conan install --install-folder conan_build --remote conancenter .

    # only build the earliest supported python version
    - uses: pypa/cibuildwheel@v2.3.1
      env:
        MACOSX_DEPLOYMENT_TARGET: 10.9
        CIBW_BUILD: cp37*
